# If you want to use precomputed noisy embeddings, set this to the path of the embeddings
noisy_embeddings_path: data/input_based_noise # null # "data/open_orca_testing_dataset_small_embeddings_512.npy"
load_noisy_embeddings: false

noise_type: "constant"

embedding_model_path: "../LLama-3.2-1B-Instruct" # "gpt2-medium" #  # "../LLama-3.2-1B-Instruct"  # "gpt2-medium"

# Parameters for the constant noise function
const_noise_params:
  noise_dist: "gaussian" # "isotropic_laplace" # "gaussian" # "laplace" "gaussian" "gaussian_with_mean"
  # The true mean and variance of the noise for the non-axial case

  gaussian:
    std: 0.3 # 0.05
    # If you want to load the mean and variance from a file, set this to true
    load_from_file: false
    mean_file: "data/small_dataset_means.npy"
    var_file: "data/small_dataset_vars.npy"

  gaussian_with_mean:
    mean: 0.0
    std: 0.3 # 0.05

  l1_laplace:
    mean: 0.00
    scale: 0.2 # 0.05

  l2_laplace:
    scale: 0.005


